name: Linting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repo
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 mypy pandas matplotlib pandas-stubs

    - name: Black
      run: black -S -l 120 . --check

    - name: Flake8
      run: flake8 --max-line-length 120

    - name: MyPy
      run: mypy .
